### ISSUE TITLE
Support extending existing ep.yml files

### ISSUE THREAD

**Issue by txels** [txels/ep#5]
So that you can extend from standard or your own templates.

``` yml
# ep.yml
ep: 0.2.0
base: python.yml
<specific overrides>
```

Ep could come with a bunch of predefined templates, and you could create your own.

Things to consider:
- replacement versus addition? when a key with a list of values already exists in base template, e.g. `run`.
